# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Api < Formula
  desc "A command line tool to work with API Specifications and code generation."
  homepage "https://github.com/boynton/api"
  version "0.3.9"
  license "Apache-2.0"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/boynton/api/releases/download/v0.3.9/api_darwin_amd64.tar.gz"
      sha256 "35fd663bd1a7d10679ad43dc7e74e0c9e11481b635ca02473772796a1ef6de26"

      def install
        bin.install "api"
      end
    end
    on_arm do
      url "https://github.com/boynton/api/releases/download/v0.3.9/api_darwin_arm64.tar.gz"
      sha256 "22aee897ab1211b1f4d660bba62fd5581345762af2af40715cc3dc2cce7a16dd"

      def install
        bin.install "api"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boynton/api/releases/download/v0.3.9/api_linux_amd64.tar.gz"
        sha256 "cc878ca7aecd305cbbe6c0e3ed4c56c7137f4708a984459caa7f2a5ef533b968"

        def install
          bin.install "api"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boynton/api/releases/download/v0.3.9/api_linux_arm64.tar.gz"
        sha256 "ccdd2a034a268c8e4374eeed810eeea0424d0f749332676ce04bd04b69d9b9a5"

        def install
          bin.install "api"
        end
      end
    end
  end

  test do
    system "#{bin}/program -v"
  end
end
