# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ell < Formula
  desc "ℒ (ell) is a LISP dialect, with semantics similar to Scheme, but adds Keywords, Structs, user-defined Types, and other features."
  homepage "https://github.com/boynton/ell"
  version "1.0.3"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/boynton/ell/releases/download/v1.0.3/ell_1.0.3_macOS_x86_64.tar.gz"
    sha256 "c06d5cce3453d823b77d7ca0dc6e01a71aff568b46998306f41bae5c2733c50b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/boynton/ell/releases/download/v1.0.3/ell_1.0.3_macOS_arm64.tar.gz"
    sha256 "330a0898fab9b85ba6826ec1940d3843fd8c12a954f3ebee65574edbb9ca4be9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/boynton/ell/releases/download/v1.0.3/ell_1.0.3_Linux_x86_64.tar.gz"
    sha256 "d306401403bc1c3b2d9f0f665b6647635e3f0f877babc413ba51dfdad98c03b4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/boynton/ell/releases/download/v1.0.3/ell_1.0.3_Linux_arm64.tar.gz"
    sha256 "2520ae5bc52668f9620c8286fe61bcadc685b7c7c524b2ba21e8a99abb995f6c"
  end

  depends_on "go"

  def install
    bin.install "ell"
  end

  test do
    system "#{bin}/program -v"
  end
end
