# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ell < Formula
  desc "ℒ (ell) is a LISP dialect."
  homepage "https://github.com/boynton/ell"
  version "1.0.4"
  license "Apache-2.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/boynton/ell/releases/download/v1.0.4/ell_1.0.4_macOS_arm64.tar.gz"
      sha256 "2d9932e3ed7436e15b7a9b498d13ae07f2d6eca562858871595738edd163feca"

      def install
        bin.install "ell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boynton/ell/releases/download/v1.0.4/ell_1.0.4_macOS_x86_64.tar.gz"
      sha256 "33fd6d3ec64ef985eebaf7867d180c12fe791cfca5eafcbd886ce1e201127c51"

      def install
        bin.install "ell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boynton/ell/releases/download/v1.0.4/ell_1.0.4_Linux_arm64.tar.gz"
      sha256 "dec59e0383c41d20a41b1adf4d2832728f24b667ba1733689a208314066bf36d"

      def install
        bin.install "ell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boynton/ell/releases/download/v1.0.4/ell_1.0.4_Linux_x86_64.tar.gz"
      sha256 "ce2df589ef08dfba0d81279fc55b9a32c506a43a2b8ab32e755e4800af9b3735"

      def install
        bin.install "ell"
      end
    end
  end

  test do
    system "#{bin}/program -v"
  end
end
