# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sadl < Formula
  desc "SADL is a general high level API description language for http-based services."
  homepage "https://github.com/boynton/sadl"
  version "1.6.1"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/boynton/sadl/releases/download/v1.6.1/sadl_1.6.1_macOS_x86_64.tar.gz"
    sha256 "d21399002f3f1af64f413d136ea917ecb33b58861673b633a2a576a044993b39"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/boynton/sadl/releases/download/v1.6.1/sadl_1.6.1_macOS_arm64.tar.gz"
    sha256 "8ffa337878b529caa17f0a311dea7bace8d9f3f1f089030ea8f9eda732a6bcca"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/boynton/sadl/releases/download/v1.6.1/sadl_1.6.1_Linux_x86_64.tar.gz"
    sha256 "10030fea326267b77fbb0ca7bd22d0345801cbc05c855f2f5f5cf2e76ce3c335"
  end

  depends_on "go"

  def install
    bin.install "sadl"
  end
end
