# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smithy < Formula
  desc "A Go-based tool to work with Smithy API Specifications."
  homepage "https://github.com/boynton/smithy"
  version "0.4.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/boynton/smithy/releases/download/v0.4.9/smithy_0.4.9_macOS_arm64.tar.gz"
      sha256 "7ad74693346daed2946a83ff07491e618118205b0ccee0baf2ba6b0246a492ef"

      def install
        bin.install "smithy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boynton/smithy/releases/download/v0.4.9/smithy_0.4.9_macOS_x86_64.tar.gz"
      sha256 "6651ae8df4c343c90e72992f9f5f7af9a692c434f0a0e0778ff3a892bcc3f729"

      def install
        bin.install "smithy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boynton/smithy/releases/download/v0.4.9/smithy_0.4.9_Linux_arm64.tar.gz"
      sha256 "4dedcf8bb6b62d159975f3f03a7e08947c6fb448c8193ffac3a459e293e1521d"

      def install
        bin.install "smithy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boynton/smithy/releases/download/v0.4.9/smithy_0.4.9_Linux_x86_64.tar.gz"
      sha256 "70dfce14d1b612453b5bd5861c0ce7ab283da5d7a0ca89f82cced77f84749f10"

      def install
        bin.install "smithy"
      end
    end
  end

  depends_on "go"

  test do
    system "#{bin}/program -v"
  end
end
